r"""
GL(2,R)-orbit closure of translation surfaces

.. TODO::

    - Theorem 1.9 of Alex Wright: the field of definition is contained in the field generated by
      the ratio of circumferences. We should provide a method, .reset_field_of_definition or
      something similar

"""

# ****************************************************************************
#  This file is part of sage-flatsurf.
#
#        Copyright (C) 2019-2026 Julian Rüth
#                      2020      Vincent Delecroix
#
#  sage-flatsurf is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  sage-flatsurf is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with sage-flatsurf. If not, see <https://www.gnu.org/licenses/>.
# ****************************************************************************

from sage.all import FreeModule, matrix, identity_matrix, ZZ, QQ, Unknown, vector, prod, cached_method, SageObject


class GL2ROrbitClosure(SageObject):
    r"""
    Lower bound approximation to the tangent space of a GL(2,R)-orbit closure of a
    linear family of translation surfaces.

    EXAMPLES::

        sage: from flatsurf import polygons, similarity_surfaces
        sage: from flatsurf import GL2ROrbitClosure  # optional: pyflatsurf

        sage: T = polygons.triangle(3, 3, 5)
        sage: S = similarity_surfaces.billiard(T)
        sage: S = S.minimal_cover(cover_type="translation")
        sage: GL2ROrbitClosure(S)  # optional: pyflatsurf  # random output due to deprecation warnings in some versions of cppyy
        GL(2,R)-orbit closure of dimension at least 2 in H_5(4, 2^2) (ambient dimension 12)

    Computing an orbit closure over an exact real ring with transcendental elements::

        sage: from flatsurf import Polygon, EuclideanPolygonsWithAngles
        sage: from pyexactreal import ExactReals  # optional: pyexactreal  # random output due to matplotlib warnings with some combinations of setuptools and matplotlib

        sage: E = EuclideanPolygonsWithAngles((1, 5, 5, 5))
        sage: R = ExactReals(E.base_ring())  # optional: pyexactreal
        sage: slopes = E.slopes()
        sage: T = Polygon(angles=(1, 5, 5, 5), edges=[slopes[0], R.random_element(1/4) * slopes[1]])  # optional: pyexactreal
        sage: S = similarity_surfaces.billiard(T)  # optional: pyexactreal
        sage: S = S.minimal_cover(cover_type="translation")  # optional: pyexactreal
        sage: O = GL2ROrbitClosure(S); O  # optional: pyflatsurf, optional: pyexactreal
        GL(2,R)-orbit closure of dimension at least 4 in H_7(4^3, 0) (ambient dimension 17)
        sage: bound = E.billiard_unfolding_stratum('half-translation', marked_points=True).dimension()
        sage: for slope in S.slopes(1):  # long time, optional: pyflatsurf, optional: pyexactreal
        ....:     decomposition = S._decomposition(slope)
        ....:     O.update_tangent_space_from_flow_decomposition(decomposition)
        ....:     if O.dimension() == bound: break
        sage: O  # long time, optional: pyflatsurf, optional: pyexactreal
        GL(2,R)-orbit closure of dimension at least 8 in H_7(4^3, 0) (ambient dimension 17)

    TESTS::

        sage: from flatsurf import translation_surfaces
        sage: x = polygen(QQ)
        sage: K = NumberField(x**3 - 2, 'a', embedding=AA(2)**QQ((1,3)))
        sage: a = K.gen()
        sage: S = translation_surfaces.mcmullen_genus2_prototype(2, 1, 0, -1, a/4)

        sage: from flatsurf import GL2ROrbitClosure  # optional: pyflatsurf
        sage: O = GL2ROrbitClosure(S) # optional: pyflatsurf
        sage: O._tangent_space.base_ring()  # optional: pyflatsurf
        Number Field in a with defining polynomial x^3 - 2 with a = 1.259921049894873?

    We now illustrate the projection::

        sage: try: # optional: pyflatsurf
        ....:     V = O.proj.row_ambient_module()
        ....: except AttributeError:
        ....:     V = O.proj._row_ambient_module()
        sage: try: # optional: pyflatsurf
        ....:     H = O.proj.column_ambient_module()
        ....: except AttributeError:
        ....:     H = O.proj._column_ambient_module()
        sage: assert O.proj.rank() == H.dimension() # optional: pyflatsurf
        sage: for b in O.boundaries(): # optional: pyflatsurf
        ....:    assert (O.proj * b).is_zero()
        sage: for i, e in enumerate(O.spanning_set): # optional: pyflatsurf
        ....:     assert (O.proj * V.gen(e.index())) == H.gen(i)
    """

    def __init__(self, surface):
        from flatsurf.features import pyflatsurf_feature
        pyflatsurf_feature.require()

        if surface.__class__.__name__.startswith("FlatTriangulation<"):
            import warnings
            warnings.warn("Creating a GL2ROrbitClosure from a FlatTriangulation has been deprecated and will be removed from a future version of sage-flatsurf; create GL2ROrbitClosure from a sage-flatsurf surface directly instead")

            from flatsurf.geometry.pyflatsurf.surface import Surface_pyflatsurf

            surface = Surface_pyflatsurf(surface)

        from flatsurf.geometry.surface import Surface_base
        if not isinstance(surface, Surface_base):
            raise TypeError("surface must be a translation surface")

        from flatsurf.geometry.categories import TranslationSurfaces
        if surface not in TranslationSurfaces():  # pyright: ignore[reportCallIssue]
            raise NotImplementedError(
                "cannot compute orbit closure of a non-translation surface"
                )

        if not surface.is_connected():
            raise NotImplementedError(
                "cannot compute orbit closures for non-connected surfaces"
            )

        self._surface = surface
        self._tangent_space = LazyTangentSpace(surface, self.ambient_dimension())

        for v in self.cohomology().tautological_subspace().basis():
            self.update_tangent_space_from_cohomology_class(v)

    @cached_method
    def homology(self, relative=True):
        r"""
        Return the (relative) homology used in the orbit closure computations.

        EXAMPLES::

            sage: from flatsurf import polygons, similarity_surfaces
            sage: from flatsurf import GL2ROrbitClosure  # optional: pyflatsurf

            sage: T = polygons.triangle(3, 3, 5)
            sage: S = similarity_surfaces.billiard(T)
            sage: S = S.minimal_cover(cover_type="translation")
            sage: O = GL2ROrbitClosure(S)  # optional: pyflatsurf

            sage: O.homology()  # optional: pyflatsurf
            H₁(Minimal Translation Cover of Genus 0 Rational Cone Surface built from 2 isosceles triangles, {...})

            sage: O.homology(relative=False)  # optional: pyflatsurf
            H₁(Minimal Translation Cover of Genus 0 Rational Cone Surface built from 2 isosceles triangles)

        """
        return self._surface.homology(relative=self._surface.vertices() if relative else None)

    def dimension(self):
        r"""
        Return the current complex dimension of the GL(2,R)-orbit closure.

        Note that this is not the dimension of the orbit closure but only a
        lower bound. It is always at least 2 (coming from a GL(2,R)-orbit).
        The current tangent space can be refined via
        :meth:`update_tangent_space_from_flow_decomposition` and
        :meth:`update_tangent_space_from_vector`.

        EXAMPLES::

            sage: from flatsurf import Polygon, similarity_surfaces
            sage: from flatsurf import GL2ROrbitClosure  # optional: pyflatsurf
            sage: T = Polygon(angles=(1, 3, 5))
            sage: S = similarity_surfaces.billiard(T)
            sage: S = S.minimal_cover(cover_type="translation")
            sage: O = GL2ROrbitClosure(S)  # optional: pyflatsurf
            sage: O.dimension()  # optional: pyflatsurf
            2
            sage: bound = T.category().billiard_unfolding_stratum('half-translation', marked_points=True).dimension()
            sage: for slope in S.slopes(bound=1, algorithm="byAngle"):  # long time, optional: pyflatsurf
            ....:     decomposition = S._decomposition(slope)
            ....:     if O.dimension() == bound: break
            ....:     O.update_tangent_space_from_flow_decomposition(decomposition)
            ....:     print(O.dimension())
            3
            5
            5
            7
            9
            10

        """
        return self._tangent_space.dimension()

    def ambient_stratum(self):
        r"""
        Return the stratum of Abelian differentials this surface belongs to.

        EXAMPLES::

            sage: from flatsurf import Polygon, similarity_surfaces
            sage: from flatsurf import GL2ROrbitClosure # optional: pyflatsurf
            sage: T = Polygon(angles=(1, 3, 5))
            sage: S = similarity_surfaces.billiard(T)
            sage: S = S.minimal_cover(cover_type="translation")
            sage: O = GL2ROrbitClosure(S)  # optional: pyflatsurf
            sage: O.ambient_stratum()  # optional: pyflatsurf
            H_3(4, 0^4)

        """
        return self._surface.stratum()

    def ambient_dimension(self):
        return self.homology().betti_number()

    def base_ring(self):
        r"""
        Return the ring of coefficients for the tangent space.

        EXAMPLES::

            sage: from flatsurf import Polygon, similarity_surfaces
            sage: from flatsurf import GL2ROrbitClosure # optional: pyflatsurf
            sage: T = Polygon(angles=(1, 3, 5))
            sage: S = similarity_surfaces.billiard(T)
            sage: S = S.minimal_cover(cover_type="translation")
            sage: O = GL2ROrbitClosure(S)  # optional: pyflatsurf
            sage: O.base_ring()  # optional: pyflatsurf
            Number Field in c with defining polynomial x^6 - 6*x^4 + 9*x^2 - 3 with c = 1.969615506024417?

        ::

            sage: from flatsurf import Polygon, EuclideanPolygonsWithAngles
            sage: from pyexactreal import ExactReals  # optional: pyexactreal  # random output due to matplotlib warnings with some combinations of setuptools and matplotlib

            sage: E = EuclideanPolygonsWithAngles((1, 5, 5, 5))
            sage: R = ExactReals(E.base_ring())  # optional: pyexactreal
            sage: slopes = E.slopes()
            sage: T = Polygon(angles=(1, 5, 5, 5), edges=[slopes[0], R.random_element(1/4) * slopes[1]])  # optional: pyexactreal
            sage: S = similarity_surfaces.billiard(T)  # optional: pyexactreal
            sage: S = S.minimal_cover(cover_type="translation")  # optional: pyexactreal
            sage: O = GL2ROrbitClosure(S)  # optional: pyflatsurf, optional: pyexactreal
            sage: O.base_ring()  # optional: pyflatsurf, optional: pyexactreal
            Number Field in c0 with defining polynomial x^2 - 2 with c0 = 1.414213562373095?

        """
        base_ring = self._surface.base_ring()

        from pyexactreal.exact_reals import ExactReals
        if isinstance(base_ring, ExactReals):
            # Determine the ring underlying the exact reals and convert to the
            # standard SageMath representation, i.e., NumberField instead of
            # RealEmbeddedNumberField.
            base_ring = base_ring.base_ring()
            if base_ring not in [ZZ, QQ]:
                base_ring = base_ring.number_field

        return base_ring

    def _repr_(self):
        return f"GL(2,R)-orbit closure of dimension at least {self.dimension()} in {self.ambient_stratum()} (ambient dimension {self.d})"

    def tangent_space_basis(self):
        r"""
        Return a basis of the tangent space constructed so far as a subspace of relative cohomology.

        EXAMPLES::

            sage: from flatsurf import translation_surfaces
            sage: from flatsurf import GL2ROrbitClosure # optional: pyflatsurf
            sage: x = polygen(QQ)
            sage: K.<a> = NumberField(x^3 - 2, embedding=AA(2)**(1/3))
            sage: S = translation_surfaces.mcmullen_L(1,1,1,a)
            sage: O = GL2ROrbitClosure(S) # optional: pyflatsurf
            sage: O.tangent_space_basis()
            [(1, 0, a, -a), (1, -1, 1, 0)]

        # TODO: Once this uses the homology machinery, add the corresponding cohomology classes.

        """
        # TODO: Return a subspace of cohomology instead.
        return self._tangent_space.basis()

    def is_teichmueller_curve(self, bound, limit=-1):
        r"""
        Search for a direction which is either
        * completely periodic with incomensurable moduli or
        * with at least one cylinder and at least one minimal component.

        Return ``False`` if such a direction is found and ``Unknown`` otherwise.

        INPUT:

        - ``bound`` -- consider directions coming from saddle connections up to this length
        - ``limit`` -- the number of Zorich induction steps to perform to
          determine whether a flow component might be a cylinder; if -1, the
          default, then induction steps are performed until the component is
          determined to be a cylinder or minimal.

        EXAMPLES::

            sage: from flatsurf import polygons, similarity_surfaces
            sage: from flatsurf import GL2ROrbitClosure  # optional: pyflatsurf
            sage: for a in range(1,6):  # long time (8s), optional: pyflatsurf
            ....:     for b in range(a,6):
            ....:         for c in range(b,6):
            ....:             if a + b + c > 7 or gcd([a,b,c]) != 1:
            ....:                 continue
            ....:             T = polygons.triangle(a, b, c)
            ....:             S = similarity_surfaces.billiard(T)
            ....:             S = S.minimal_cover(cover_type="translation")
            ....:             O = GL2ROrbitClosure(S)
            ....:             if O.is_teichmueller_curve(3, 50) != False:
            ....:                 print(a,b,c)
            1 1 1
            1 1 2
            1 1 4
            1 2 2
            1 2 3
            1 3 3
        """
        if self._surface.base_ring() in [ZZ, QQ]:
            # square tiled surface
            return True

        if self.dimension() > 2:
            # too large orbit closure
            return False

        k = self.field_of_definition()
        if k in [ZZ, QQ]:
            # square tiled
            return True

        nv = len(self._flat_triangulation().vertices())
        ne = len(self._flat_triangulation().edges())
        nf = len(self._flat_triangulation().faces())
        genus = (ne - nv - nf) // 2 + 1
        if k.degree() > genus or not k.is_totally_real():
            return False

        for slope in self._surface.slopes(bound=bound, algorithm="byAngle"):
            decomposition = self._surface._decomposition(slope, limit=limit)
            if (
                decomposition.parabolic() == False
            ):  # we are comparing to a boost tribool so this cannot be replaced by "is False"  # noqa
                return False

        return Unknown

    def cylinder_deformation_subspace(self, decomposition):
        r"""
        Return a basis of the subspace included in the tangent space to the
        GL(2,R)-orbit closure computed from the flow decomposition
        ``decomposition``.

        From A. Wright Cylinder Deformation Theorem.
        """
        # TODO: Return a subspace of relative cohomology.
        # TODO: Add example.

        module_fractions = self.cylinder_modules(decomposition)
        circumferences = self.cylinder_circumferences(decomposition)

        return list(self._tangent_space.cylinder_deformation_subspace(module_fractions, circumferences))

    def update_tangent_space_from_flow_decomposition(self, decomposition):
        r"""
        Update the current tangent space by using the cylinder deformation vectors from ``decomposition``.

        EXAMPLES::

            sage: from flatsurf import polygons, similarity_surfaces
            sage: from flatsurf import GL2ROrbitClosure  # optional: pyflatsurf

            sage: T = polygons.triangle(1, 2, 5)
            sage: S = similarity_surfaces.billiard(T)
            sage: S = S.minimal_cover(cover_type="translation")
            sage: O = GL2ROrbitClosure(S)  # optional: pyflatsurf
            sage: for slope in S.slopes(bound=1):  # long time (1s), optional: pyflatsurf
            ....:     d = S._decomposition(slope)
            ....:     O.update_tangent_space_from_flow_decomposition(d)
            sage: assert O.dimension() == 2  # long time (above), optional: pyflatsurf

        TESTS:

        A regression test for  https://github.com/flatsurf/sage-flatsurf/pull/69::

            sage: from itertools import islice
            sage: from flatsurf import polygons, similarity_surfaces
            sage: from flatsurf import GL2ROrbitClosure  # optional: pyflatsurf

            sage: for (a,b,c,dim) in [(3,2,2,7), (4,2,1,8), (4,4,3,11), (5,3,3,11), (5,4,4,13), (5,5,3,13)]: # long time, optional: pyflatsurf
            ....:     T = polygons.triangle(a, b, c)
            ....:     S = similarity_surfaces.billiard(T)
            ....:     S = S.minimal_cover(cover_type="translation")
            ....:     O = GL2ROrbitClosure(S)  # optional: pyflatsurf
            ....:     nsteps = 0
            ....:     for slope in islice(S.slopes(bound=3, algorithm="byAngle"), 10):
            ....:         d = S._decomposition(slope, limit=100)
            ....:         O.update_tangent_space_from_flow_decomposition(d)
            ....:         nsteps += 1
            ....:         if O.dimension() == dim:
            ....:             break
            ....:     print("(%d, %d, %d): %d" % (a, b, c, nsteps))
            (3, 2, 2): 5
            (4, 2, 1): 4
            (4, 4, 3): 4
            (5, 3, 3): 4
            (5, 4, 4): 7
            (5, 5, 3): 4

        """
        circumferences = self.cylinder_circumferences(decomposition)
        modules = self.cylinder_modules(decomposition)

        self._tangent_space.update_from_flow_decomposition(circumferences, modules)

    def update_tangent_space_from_vector(self, v):
        r"""
        Enlarge the currently determined tangent space with ``v`` which is a
        direction in the tangent space encoded as a relative cohomology class.

        EXAMPLES::

            TODO

        """
        # TODO: v should probably be required to be a relative cohomology class
        self._tangent_space.update_from_vector(v)

    def __eq__(self, other):
        r"""
        Return whether ``other`` was built starting from the same surface than
        this orbit closure.

        EXAMPLES::

            sage: from flatsurf import polygons, similarity_surfaces
            sage: from flatsurf import GL2ROrbitClosure  # optional: pyflatsurf

            sage: T = polygons.triangle(1, 2, 5)
            sage: S = similarity_surfaces.billiard(T)
            sage: S = S.minimal_cover(cover_type="translation")
            sage: GL2ROrbitClosure(S) == GL2ROrbitClosure(S) # optional: pyflatsurf
            True

        """
        return type(self) == type(other) and self._surface == other._surface

    def __ne__(self, other):
        r"""
        Return whether ``other`` was not built starting from the same surface
        than this orbit closure.

        EXAMPLES::

            sage: from flatsurf import polygons, similarity_surfaces
            sage: from flatsurf import GL2ROrbitClosure  # optional: pyflatsurf

            sage: T = polygons.triangle(1, 2, 5)
            sage: S = similarity_surfaces.billiard(T)
            sage: S = S.minimal_cover(cover_type="translation")
            sage: GL2ROrbitClosure(S) != GL2ROrbitClosure(S) # optional: pyflatsurf
            False

        """
        return not (self == other)

    def __hash__(self):
        r"""
        Return a hash value of this object compatible with equality operators.

        EXAMPLES::

            sage: from flatsurf import polygons, similarity_surfaces
            sage: from flatsurf import GL2ROrbitClosure  # optional: pyflatsurf

            sage: T = polygons.triangle(1, 2, 5)
            sage: S = similarity_surfaces.billiard(T)
            sage: S = S.minimal_cover(cover_type="translation")
            sage: O = GL2ROrbitClosure(S)  # optional: pyflatsurf
            sage: hash(O) == hash(O)  # optional: pyflatsurf
            True

        """
        return hash(self._surface)

    def __reduce__(self):
        r"""
        Return a serializable representation of this Orbit Closure.

        EXAMPLES::

            sage: from flatsurf import polygons, similarity_surfaces
            sage: from flatsurf import GL2ROrbitClosure  # optional: pyflatsurf

            sage: T = polygons.triangle(1, 2, 5)
            sage: S = similarity_surfaces.billiard(T)
            sage: S = S.minimal_cover(cover_type="translation")
            sage: O = GL2ROrbitClosure(S)  # optional: pyflatsurf
            sage: loads(dumps(O)) == O  # optional: pyflatsurf  # long time (6s, #123)
            True
        """
        return (
            GL2ROrbitClosure,
            (self._surface,),
        )


class LazyTangentSpace:
    r"""
    Helper for :class:`GL2ROrbitClosure` that keeps track of the tangent space
    computed thus far.

    EXAMPLES::

        # TODO

    """
    def __init__(self, surface, ambient_dimension):
        self._surface_base_ring = surface.base_ring()
        self._ambient_dimension = ambient_dimension

        self._pending_for_dimension = []
        self._pending_for_basis = []

        # The tangent space we have constructed so far as relative cohomology classes.
        # Can only be safely accessed after a call to _require_basis.
        # Note that we don't use Sage vector spaces because they are usually
        # way too slow (in particular we avoid calling .echelonize())
        # TODO: Actually use relative cohomology classes.
        self._basis = []

        # The tangent space vectors reduced modulo a prime ideal _p of the
        # number field containing its entries.
        # This is used to determine the dimension of the tangent space without
        # constructing the full matrix U and computing its rank.
        from sage.all import GF
        self._U_bar = matrix(GF(2), 0, ambient_dimension)
        self._primes = iter(self._create_primes())
        self._prime = None

    @cached_method
    def base_ring(self):
        # TODO: Examples and docstring.
        # TODO: This doesn't really have anything to do with "vectors". We
        # should reimplement this in sage-flatsurf and drop the implementation
        # in pyflatsurf.
        from pyflatsurf.vector import Vectors
        return Vectors(self._surface_base_ring)._algebraic_ring()

    def _create_primes(self):
        r"""
        Returns an infinite sequence of big prime ideals of the
        :meth:`base_ring` to speed up operations by computing the basis of the
        tangent space modulo these primes.

        EXAMPLES::

            TODO

        """
        from sage.all import next_prime

        p = 2**60

        while True:
            p = next_prime(p)

            yield ZZ.valuation(p).extensions(self.base_ring())[0]

    def _require_dimension(self):
        r"""
        Ensure that all the dimension reported by this tangent space
        incorporated all the data submitted via the ``_update_dimension...()``
        calls.

        Automatically called when :meth:`dimension` is accessed.
        """
        for item in self._pending_for_dimension:
            self._update_dimension(item)

        self._pending_for_dimension = []

    def _require_basis(self, require_dimension=True):
        r"""
        Ensure that the basis reported by this tangent space incorporated all
        the data submitted via the ``_update_dimension...()`` calls.

        Automatically called when :meth:`basis` is accessed.

        EXAMPLES::

            TODO

        """
        if require_dimension:
            self._require_dimension()

        for item, row in self._pending_for_basis:
            self._update_basis(item, row)

        self._pending_for_basis = []

    def dimension(self):
        r"""
        Return the current dimension of this tangent space.

        EXAMPLES::

            # TODO

        """
        self._require_dimension()

        return self._U_bar.nrows()

    def basis(self):
        r"""
        Return a basis of the currently known tangent space as relative
        cohomology classes.

        EXAMPLES::

            # TODO

        """
        self._require_basis()

        # TODO: Ensure that these are actually cohomology classes
        return self._basis[:]

    def _update_dimension(self, item):
        r"""
        Incorporate ``item`` into the known dimension of this tangent space.

        This is a helper method for :meth:`_require_dimension`.

        .. SEEALSO::

            :meth:`update_basis` for the corresponding operation to incorporate
            information into the currently known basis.

        EXAMPLES::

            TODO

        """
        if isinstance(item, tuple):
            increases = self._update_dimension_from_decomposition(*item)
        else:
            increases = self._update_dimension_from_vector(item)

        self._pending_for_basis.append((item, increases))

    def _update_dimension_from_decomposition(self, circumferences, module_fractions) -> list[int]:
        r"""
        Incorporate the cylinder ``circumferences`` and their moduli into known
        dimension of this tangent space.

        This is a helper method for :meth:`_update_dimension`.

        Return the indexes of the tangent space vectors extracted from the data
        that actually lead to an increase in the dimension.

        EXAMPLES::

            # TODO

        """
        increases = []

        for i, v in enumerate(self.cylinder_deformation_subspace(circumferences, module_fractions, reduced=True)):
            if self._update_dimension_from_reduced_vector(v):
                increases.append(i)

        return increases

    def _reduce_vector(self, v):
        r"""
        Return a reduction of the vector ``v`` (defined over the
        :meth:`base_ring`) modulo a big prime ideal.

        This is a helper method for :meth:`_update_dimension_from_vector`.

        EXAMPLES::

            TODO

        """
        assert v.base_ring() is self.base_ring(), f"Expected vector over {self.base_ring()} but found vector over {v.base_ring()}"

        while True:
            p = self._require_p()

            try:
                return v.apply_map(phi=p.reduce, R=p.residue_field())
            except ValueError:
                self._require_p(force_next=True)

    def _decomposition(self, v):
        r"""
        Write ``v`` as a linear combination over a transcendental basis.

        This is a trivial operation unless working over exact-real rings.

        This is a helper method for :meth:`_update_dimension_from_vector`.

        EXAMPLES::

            TODO

        """
        # TODO: Fix upstream in pyflatsurf
        if v.base_ring() is QQ:
            return [(QQ.one(), v)]

        # TODO: This doesn't really have anything to do with "vectors". We
        # should reimplement this in sage-flatsurf and drop the implementation
        # in pyflatsurf.
        from pyflatsurf.vector import Vectors
        return Vectors(self._surface_base_ring).decomposition(v)

    def _update_dimension_from_vector(self, v) -> list[int]:
        r"""
        Incorporate a direction ``v`` in the tangent space into the known
        dimension of this tangent space.

        This is a helper method for :meth:`_update_dimension`.

        EXAMPLES::

            TODO

        """
        # TODO: Ensure that v is a relative cohomology class and document that.
        assert v.base_ring() is self._surface_base_ring

        decompositions = []

        # Rewrite v as vectors over base_ring(), i.e., the underlying SageMath
        # number field. (This extracts the different components of a vector
        # over exact-real. Otherwise, this is just a simple cast between an
        # e-antic number field and a SageMath number field.)
        for i, (_, w) in enumerate(self._decomposition(v)):
            assert all(x.parent() is self.base_ring() for x in w)

            w = vector(self.base_ring(), w)
            if self._update_dimension_from_reduced_vector(self._reduce_vector(w)):
                decompositions.append(i)

        return decompositions

    def _update_dimension_from_reduced_vector(self, v) -> bool:
        r"""
        Incorporate a direction ``v`` in the tangent space (reduced module a
        prime) into the known dimension of this tangent space.

        This is a helper method for :meth:`_update_dimension_from_vector`.

        EXAMPLES::

            TODO
        """
        if self._U_bar.nrows() == self._ambient_dimension:
            return False

        U_bar = matrix(self._U_bar.base_ring(), self._U_bar.nrows() + 1, self._U_bar.ncols(), self._U_bar.rows() + [v])

        if U_bar.rank() != U_bar.nrows():
            return False

        self._U_bar = U_bar
        return True

    def _update_basis(self, item, rows: list[int]):
        r"""
        Enlarge the recorded base for this tangent space from the ``item``.

        The item might encode several tangent space vectors, e.g., if it is a
        flow decomposition or if it is a vector over some exact-reals. For that
        purpose, ``rows`` contains the indexes of the resulting tangent space
        vectors encoded that lead to an increase in the dimension computation
        and are therefore the indexes that must lead to an increase in the
        basis.

        This is a helper method for :meth:`_require_basis`.

        .. SEEALSO::

            :meth:`_require_dimension` for the corresponding method that
            ensures the correct dimension and also sets up the ``rows`` list
            for this method.

        EXAMPLES::

            TODO
        """
        if isinstance(item, tuple):
            assert len(item) == 2, "item must be a pair of circumferences and moduli"
            self._update_basis_from_decomposition(item[0], item[1], rows)
        else:
            self._update_basis_from_vector(item, rows)

    def _update_basis_from_decomposition(self, circumferences, module_fractions, rows: list[int]):
        r"""
        Enlarge the recorded basis for this tangent space from the circumferences and moduli.

        See :meth:`_update_basis` for the meaning of ``rows``.

        This is a helper method for :meth:`_update_basis`.

        EXAMPLES::

            TODO

        """
        for v in self.cylinder_deformation_subspace(circumferences, module_fractions, rows=rows):
            self._basis.append(v)

    def _update_basis_from_vector(self, v, rows: list[int]):
        r"""
        Enlarge the recorded basis for this tangent space from the tangent vector ``v``.

        See :meth:`_update_basis` for the meaning of ``rows``.

        This is a helper method for :meth:`_update_basis`.

        EXAMPLES::

            TODO
        """
        # Rewrite v as vectors over base_ring(), i.e., the underlying SageMath
        # number field. (This extracts the different components of a vector
        # over exact-real. Otherwise, this is just a simple cast between an
        # e-antic number field and a SageMath number field.)
        for i, (_, w) in enumerate(self._decomposition(v)):
            if i not in rows:
                continue

            assert len(self._basis) < self._U_bar.nrows()

            assert all(x.parent() is self.base_ring() for x in w)
            w = vector(self.base_ring(), w)
            self._basis.append(w)

    def _require_p(self, force_next=None):
        r"""
        Ensure that ``_prime`` is a prime ideal of :meth:`base_ring` such that
        the known basis of the tangent space can be reduced module that prime.

        If ``force_next`` is set, then we advance to the next prime even if
        already had already been selected.

        EXAMPLES::

            TODO

        """
        if force_next or self._prime is None:
            self._require_basis(require_dimension=False)
            assert len(self._basis) == self._U_bar.nrows()
            while True:
                self._prime = next(self._primes)

                try:
                    reduced_basis = [v.apply_map(phi=self._prime.reduce(), R=self._prime.residue_field()) for v in self._basis]
                except ValueError:
                    continue

                self._U_bar = matrix(self._prime.residue_field(), self._U_bar.nrows(), self._U_bar.ncols(), reduced_basis)
                break
        return self._prime

    def update_from_flow_decomposition(self, circumferences, modules):
        r"""
        Enlarge this tangent space with the ``circumferences`` and ``modules``
        derived from a flow decomposition.

        This is a helper method for
        :meth:`GL2ROrbitClosure.update_tangent_space_from_flow_decomposition`.

        EXAMPLES::

            TODO

        """
        # TODO: Should circumferences and modules be different types?
        self._pending_for_dimension.append((circumferences, modules))

    def update_from_vector(self, v):
        # TODO: Actually make v be a rel cohomology class.
        r"""
        Enlarge this tangent space with the tangent space element ``v``.

        This is a helper method for
        :meth:`GL2ROrbitClosure.update_tangent_space_from_vector`.

        INPUT:

        - ``v`` -- a relative cohomology class representing a direction in the
          tangent space.

        EXAMPLES::

            TODO

        """
        if len(v) != self._ambient_dimension:
            raise TypeError(f"Expected vector of length {self._ambient_dimension} but found vector of length {len(v)}")

        if v.base_ring() is not self._surface_base_ring:
            raise NotImplementedError(f"Expected vector over {self._surface_base_ring} but found vector over {v.base_ring()}")

        self._pending_for_dimension.append(v)

    @staticmethod
    def _cylinder_deformation_subspace_eliminate_denominators(fractions):
        r"""
        Given a list of ``fractions``, pairs of numerators `n_i` and
        denominators `d_i`, return a list of fractions `c n_i/d_i` scaled
        uniformly such that the value can be represented in the underlying
        ring.

        This is a helper method for meth:`cylinder_deformation_subspace`.

        EXAMPLES::

            TODO

        """
        fractions = list(fractions)
        try:
            return [x.parent()(x / y) for x, y in fractions]
        except (ValueError, ArithmeticError, NotImplementedError):
            denominators = {denominator for numerator, denominator in fractions}
            return [
                numerator * prod([d for d in denominators if denominator != d])
                for (numerator, denominator) in fractions
            ]

    def _cylinder_deformation_subspace_rational_vector(self, x):
        r"""
        Return the rational coefficients of `x` over its implicit basis,
        e.g., if `x` is in a number field K, return the coefficients of x
        in `K` as a vector space over the rationals.

        This is a helper method for :meth:`cylinder_deformation_subspace`.

        EXAMPLES::

            TODO

        """
        if x.parent() in [ZZ, QQ]:
            ret = [QQ(x)]
        elif hasattr(x, "vector"):
            ret = x.vector()
        elif hasattr(x, "renf_elem"):
            ret = x.parent().number_field(x).vector()
        elif hasattr(x, "_backend"):
            # TODO: This should probably live elsewhere.
            from flatsurf.geometry.pyflatsurf.conversion import RingConversion
            section = RingConversion.to_pyflatsurf(self.base_ring()).section

            from itertools import chain
            ret = list(
                chain(
                    *[
                        self._cylinder_deformation_subspace_rational_vector(
                            section(c)
                        )
                        for c in x._backend.coefficients()
                    ]
                )
            )
        else:
            raise NotImplementedError(
                "cannot turn {}, i.e., a {}, into a rational vector yet".format(
                    x, type(x)
                )
            )

        assert all(y in QQ for y in ret)
        return ret

    def _cylinder_deformation_subspace_unify_parent(self, modules):
        r"""
        Return all ``modules`` as elements of the same parent.

        This is a helper method for :meth:`cylinder_deformation_subspace`.

        INPUT::

        - ``modules`` -- pairs of elements, encoding ``width`` and ``height``.

        EXAMPLES::

            TODO

        """
        if hasattr(modules[0], "_backend"):
            # Make sure all modules live in the same K-Module so that .coefficients() below produces coefficient lists of the same length.
            from functools import reduce

            parent = reduce(
                lambda m, n: m.span(m, n),
                [module._backend.module() for module in modules],
                modules[0]._backend.module(),
            )
            modules = [
                module.parent()(module._backend.promote(parent)) for module in modules
            ]

        assert all(module.parent() is modules[0].parent() for module in modules)
        return modules

    def _cylinder_deformation_subspace_reduce(self, relations, circumferences, decomposed_denominators):
        r"""
        Return the provided data reduced module the prime ideal returned by :meth:`_require_p`.

        This is a helper method for :meth:`cylinder_deformation_subspace` used
        to speed up computations by then performing computations in a finite
        field instead of an unwieldy number field.

        EXAMPLES::

            TODO

        """
        assert all(denominator.parent() is self.base_ring() for denominators in decomposed_denominators for denominator in denominators)

        while True:
            prime = self._require_p()
            k = prime.residue_field()

            reduced_relations = [relation.change_ring(k) for relation in relations]
            try:
                reduced_circumferences = [circumference.change_ring(k) for circumference in circumferences]
            except ZeroDivisionError:
                self._require_p(force_next=True)
                continue

            try:
                reduced_denominators = [[prime.reduce(d) for d in ds] for ds in decomposed_denominators]
            except ValueError:
                self._require_p(force_next=True)
                continue

            return reduced_relations, reduced_circumferences, reduced_denominators

    def cylinder_deformation_subspace(self, circumferences, module_fractions, reduced=False, rows=None):
        r"""
        Return tangent vectors obtained from the cylinder ``circumferences``
        and their corresponding moduli ``module_fractions``.

        INPUT:

        - ``circumferences`` -- TODO
        - ``module_fractions`` -- TODO
        - ``reduced`` -- TODO
        - ``rows`` -- TODO

        EXAMPLES:

            TODO

        """
        assert len(circumferences) == len(module_fractions)

        if not module_fractions:
            return []

        modules = self._cylinder_deformation_subspace_eliminate_denominators(module_fractions)
        modules = self._cylinder_deformation_subspace_unify_parent(modules)

        M = matrix([self._cylinder_deformation_subspace_rational_vector(module) for module in modules])
        assert M.base_ring() is QQ
        relations = self._left_kernel_matrix(M)
        assert len(circumferences) == len(module_fractions) == relations.ncols()
        relations = self._right_kernel_matrix(relations).rows()

        # TODO: This code is horrible. Find a better way to do this.
        decomposed_denominators = [dict(self._decomposition(vector([denominator]))) for (_, denominator) in module_fractions]
        transcendentals = set(sum((list(d.keys()) for d in decomposed_denominators), []))
        decomposed_denominators = [[dd.get(transcendental, [self.base_ring().zero()])[0] for dd in decomposed_denominators] for transcendental in transcendentals]

        if reduced:
            relations, circumferences, decomposed_denominators = self._cylinder_deformation_subspace_reduce(relations, circumferences, decomposed_denominators)

        row = 0
        for relation in relations:
            for denominators in decomposed_denominators:
                assert len(relation) == len(circumferences) == len(denominators)

                skip = rows is not None and row not in rows
                row += 1

                if skip:
                    continue

                yield sum(
                    t * circumference * denominator
                    for (t, circumference, denominator) in zip(relation, circumferences, denominators)
                )

    @staticmethod
    def _right_kernel_matrix(M):
        r"""
        Compute the right kernel of the rational matrix `M`.

        This speeds up the unfortunate algorithm selection in upstream
        SageMath, see https://github.com/flatsurf/sage-flatsurf/issues/100.

        EXAMPLES::

            TODO

        """
        M = M._clear_denom()[0]

        rows = M.nrows()
        columns = M.ncols()

        # The backends cannot handle these trivial cases
        if M.ncols() == 0:
            return M.new_matrix(nrows=0, ncols=M.ncols())
        if M.nrows() == 0:
            return M.matrix_space(M.ncols(), M.ncols()).identity_matrix()

        height = M.height()

        if height >= 2**256:
            algorithm = "flint"
        elif columns >= 64 and rows >= 64:
            algorithm = "padic"
        elif rows * columns <= 32:
            algorithm = "flint"
        else:
            algorithm = "pari"

        if algorithm == "pari":
            ker = M.__pari__().matker().mattranspose().sage()
        elif algorithm == "flint":
            ker = M._rational_kernel_flint().transpose()
        else:
            ker = M._rational_kernel_iml().transpose()

        if ker.nrows() == 0 and ker.ncols() != M.ncols():
            ker = ker.new_matrix(nrows=0, ncols=M.ncols())

        return ker

    @staticmethod
    def _left_kernel_matrix(M):
        r"""
        Compute the left kernel of the rational matrix `M`.

        This speeds up the unfortunate algorithm selection in upstream
        SageMath, see https://github.com/flatsurf/sage-flatsurf/issues/100.

        EXAMPLES::

            TODO

        """
        return LazyTangentSpace._right_kernel_matrix(M.transpose())
